name: Build and deploy the docs

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-docs:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_docs.txt
        python -m pip install .
    - name: Build the docs
      run: |
        python setup.py doc -W
    - name: Deploy the docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/sphinx/html/
        force_orphan: true
